# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

require 'yaml'
vm_config = YAML.load_file('vm-config.yml')
vm_platform = vm_config['vm_platform']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = vm_config[vm_platform]['box']

  config.vm.define :docker do | docker |

    docker.vm.network 'private_network', ip: vm_config['docker']['ip_address']
    docker.vm.synced_folder '../services', '/services'

    docker.vm.provider 'virtualbox' do | vb |
      vb.memory = 4096
      vb.cpus = 4
    end

    docker.vm.provision 'shell', path: "#{vm_platform}/pre_docker_install.sh"

    docker.vm.provision 'docker', version: vm_config['docker']['version']

    vm_config['docker']['install_images'].each do | image |
      docker.vm.provision 'docker', images: [ "#{image['name']}:#{image['tag']}" ]
    end

    docker.vm.provision 'shell', path: "#{vm_platform}/post_docker_install.sh"


    vm_config['docker']['run_images'].each do | image |
      docker.vm.provision 'docker' do | d |
        d.run "#{image['name']}:#{image['tag']}",
          args: "#{image['args']}",
          daemonize: true
      end
    end

    if vm_config['docker']['install_service_images']
      docker.vm.provision 'shell', path: 'install_local_docker_images.sh'
    end

    if vm_config['docker']['install_mesos']
      docker.vm.provision 'shell', path:  "#{vm_platform}/install_mesos.sh"
    end

  end

  config.vm.define :deis do | deis |

    deis.vm.network 'private_network', ip: vm_config['deis']['ip_address']

    deis.vm.provider 'virtualbox' do | vb |
      vb.memory = 1024
      vb.cpus = 2
    end

    config.vm.provision 'shell', path: 'install_deis_workstation.sh'

    if vm_config['deis']['install_platform']
      docker.vm.provision 'shell', path:  'install_deis_platform.sh'
    end

  end

end
