# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

require 'yaml'
vm_config = YAML.load_file('vm-config.yml')
vm_platform = vm_config['vm_platform']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = vm_config[vm_platform]['box']

  config.vm.define :gocd do | gocd |

    gocd.vm.network 'private_network', ip: vm_config['gocd']['ip_address']
    gocd.vm.synced_folder '../services', '/services'

    gocd.vm.provider 'virtualbox' do | vb |
      vb.memory = vm_config['gocd']['memory']
      vb.cpus = vm_config['gocd']['cpus']
    end


    gocd.vm.provision 'shell', path: "#{vm_platform}/pre_docker_install.sh"

    gocd.vm.provision 'docker', version: vm_config['gocd']['docker_version']

    vm_config['gocd']['install_images'].each do | image |
      gocd.vm.provision 'docker', images: [ "#{image['name']}:#{image['tag']}" ]
    end

    gocd.vm.provision 'shell', path: "#{vm_platform}/post_docker_install.sh"

    # Install GoCD before running docker images since docker will need to be restarted.
    gocd.vm.provision 'shell', path:  "#{vm_platform}/install_gocd.sh"

    vm_config['gocd']['run_images'].each do | image |
      gocd.vm.provision 'docker' do | d |
        d.run "#{image['name']}:#{image['tag']}",
              args: "#{image['args']}",
            daemonize: true
      end
    end

  end

  config.vm.define :mesos_master do | mesos_master |

    mesos_master.vm.network 'private_network', ip: vm_config['mesos_master']['ip_address']
    mesos_master.vm.synced_folder '../services', '/services'

    mesos_master.vm.provider 'virtualbox' do | vb |
      vb.memory = vm_config['mesos_master']['memory']
      vb.cpus = vm_config['mesos_master']['cpus']
    end

    mesos_master.vm.provision 'shell', path: "#{vm_platform}/pre_docker_install.sh"

    mesos_master.vm.provision 'docker', version: vm_config['mesos_master']['docker_version']

    vm_config['mesos_master']['install_images'].each do | image |
      mesos_master.vm.provision 'docker', images: [ "#{image['name']}:#{image['tag']}" ]
    end

    mesos_master.vm.provision 'shell', path: "#{vm_platform}/post_docker_install.sh"


    vm_config['mesos_master']['run_images'].each do | image |
      mesos_master.vm.provision 'docker' do | d |
        d.run "#{image['name']}:#{image['tag']}",
          args: "#{image['args']}",
          daemonize: true
      end
    end

    mesos_master.vm.provision 'shell', path:  "#{vm_platform}/install_mesos_master.sh"

  end

  config.vm.define :mesos_slave do | mesos_slave |

    mesos_slave.vm.network 'private_network', ip: vm_config['mesos_slave']['ip_address']
    mesos_slave.vm.synced_folder '../services', '/services'

    mesos_slave.vm.provider 'virtualbox' do | vb |
      vb.memory = vm_config['mesos_slave']['memory']
      vb.cpus = vm_config['mesos_slave']['cpus']
    end

    mesos_slave.vm.provision 'shell', path: "#{vm_platform}/pre_docker_install.sh"

    mesos_slave.vm.provision 'docker', version: vm_config['mesos_slave']['docker_version']

    vm_config['mesos_slave']['install_images'].each do | image |
      mesos_slave.vm.provision 'docker', images: [ "#{image['name']}:#{image['tag']}" ]
    end

    mesos_slave.vm.provision 'shell', path: "#{vm_platform}/post_docker_install.sh"


    vm_config['mesos_slave']['run_images'].each do | image |
      mesos_slave.vm.provision 'docker' do | d |
        d.run "#{image['name']}:#{image['tag']}",
              args: "#{image['args']}",
            daemonize: true
      end
    end

    mesos_slave.vm.provision 'shell', path:  "#{vm_platform}/install_mesos_slave.sh"

  end

end