FROM gocd/gocd-agent:latest

ADD go-agent-start.sh /etc/service/go-agent/run

ENV AGENT_RESOURCES java8

RUN sudo add-apt-repository ppa:webupd8team/java
RUN sudo apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN sudo apt-get install -y oracle-java8-installer
RUN sudo sudo apt-get install -y oracle-java8-set-default
