# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

# Can be 7 or 8
java_version = '8'

# Can be 2.0 or 2.1
cassandra_version = '2.1'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network 'private_network', ip: '172.17.8.10'
  config.vm.synced_folder '../../services', '/services'

  config.vm.provider 'virtualbox' do |vb|
    config.vm.provider 'virtualbox' do |vb|
      vb.memory = 4096
      vb.cpus = 4
    end
  end

  config.vm.provision 'shell',
    inline: 'sudo echo DOCKER_OPTS=\\"\\$DOCKER_OPTS --insecure-registry 172.17.8.0/24\\" >> /etc/default/docker'

  config.vm.provision 'docker', version: '1.6.2'

  config.vm.provision 'docker' do | d |
    d.pull_images 'registry:0.9.1'
    d.pull_images 'google/cadvisor:latest'
    d.pull_images 'debian:jessie'
    d.pull_images "java:#{java_version}"
    d.pull_images "cassandra:#{cassandra_version}"

# Optionally run docker containers
#
#    d.run 'cassandra:2.1',
#      args: '--name cassandra-1 -p 9042:9042',
#      daemonize: true
#
#    d.run 'registry:0.9.1',
#      args: '--name docker-registry -p 5000:5000',
#      daemonize: true
#
#    d.run 'google/cadvisor:latest',
#      args: '--name cadvisor -p 80:8080',
#      daemonize: true

  end

  config.vm.provision 'shell', path: 'install_local_docker_images.sh'
  config.vm.provision 'shell', path: 'install_mesos.sh'
  config.vm.provision 'shell', path: 'install_deis_workstation.sh'
end
