apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: echo-service
  name: echo-service
spec:
  replicas: 1
  selector:
    name: echo-service
  template:
    metadata:
      labels:
        name: echo-service
    spec:
      containers:
        - name: echo-service
          image: 10.245.1.100:5000/example/java-echo:0.1
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              hostPort: 31000
              name: api
            - containerPort: 8081
              hostPort: 31001
              name: admin
