apiVersion: v1
kind: Service
metadata:
  labels:
    name: echo-service
  name: echo-service
spec:
  ports:
    - port: 8080
      name: api
    - port: 8081
      name: admin
  selector:
    name: echo-service

