FROM gocd/gocd-agent:latest

ADD go-agent-start.sh /etc/service/go-agent/run

RUN curl -sSL http://deis.io/deis-cli/install.sh | sh
RUN sudo ln -fs $PWD/deis /usr/local/bin/deis

RUN curl -sSL http://deis.io/deisctl/install.sh | sudo sh -s 1.7.3
RUN sudo ln -fs $PWD/deisctl /usr/local/bin/deisctl

ADD insecure_private_key /data/insecure_private_key

RUN eval `ssh-agent -s`
RUN ssh-add /data/insecure_private_key

ENV AGENT_RESOURCES deis
