FROM gocd/gocd-agent:latest

ADD go-agent-start.sh /etc/service/go-agent/run

ENV AGENT_RESOURCES cucumber

# Install Ruby
RUN sudo apt-get update
RUN sudo apt-get install -y build-essential
RUN sudo apt-get install -y ruby-full
RUN gem install bundler
RUN gem install cucumber

RUN sudo apt-get remove --purge -y  build-essential
RUN sudo apt-get autoremove -y
