# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

# Can be 7 or 8
java_version = '8'

# Can be 2.0 or 2.1
cassandra_version = '2.1'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Centos 7.0 had problems with Vagrant Docker provisioner
  config.vm.box = 'chef/centos-7.1'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network 'private_network', ip: '192.168.11.100'
  config.vm.synced_folder '../../services', '/services'

  config.vm.provider 'virtualbox' do |vb|
    config.vm.provider 'virtualbox' do |vb|
      vb.memory = 4096
      vb.cpus = 4
      end
  end

  # Added to fix Vagrant bug #5709 as of 5/27/2015 to activate the private network interface
  config.vm.provision 'shell', inline: 'nmcli connection reload; systemctl restart network.service'

  # Adding group 'docker' is workaround for bug #5686 in Vagrant Docker Provisioner as of 5/26/15
  config.vm.provision 'shell', inline: 'groupadd -f docker'

  # CentOS Vagrant Docker provisioner does not support pinning versions
  #config.vm.provision 'docker', version: '1.6.2'

  config.vm.provision 'docker' do | d |

    d.pull_images 'registry:0.9.1'
    d.pull_images 'google/cadvisor:latest'
    d.pull_images 'debian:jessie'
    d.pull_images "java:#{java_version}"
    d.pull_images "cassandra:#{cassandra_version}"

  end

  $script = <<SCRIPT
    sudo sed -i 's/other_args=/other_args="--insecure-registry 192.168.0.0\\/16"/g' /etc/sysconfig/docker
    sudo service docker restart
SCRIPT

  config.vm.provision 'shell', inline: $script

  config.vm.provision 'docker' do | d |

    d.run 'cassandra:2.1',
        args: '--name cassandra-1 -p 9042:9042',
      daemonize: true

    d.run 'registry:0.9.1',
        args: '--name docker-registry -p 5000:5000',
      daemonize: true

  end

  config.vm.provision 'shell', path: 'install_local_docker_images.sh'
  config.vm.provision 'shell', path: 'install_mesos.sh'

end
